version: '3'

services:
  meican:
    image:  ghcr.io/ufrgs-hyman/meican/meican-app:3.3.0-rc
    env_file:
      - ./env/.env
    container_name: meican-app
    tty: true
    restart: always
    ports:
      - "${MEICAN_PORT:-80}:80"
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:5.7
    container_name: meican-db
    volumes:
      - db-meican:/var/lib/mysql
    restart: always
    env_file:
      - ./env/.env
  
volumes:
  db-meican: