version: '3'

services:
  meican:
    image: meican_image_$MEICAN_INSTANCE:$MEICAN_INSTANCE
    build:
      context: .
      args:
        - MEICAN_INSTANCE
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MEICAN_INSTANCE
      - MEICAN_DIR=/home/meican/meican-$MEICAN_INSTANCE
    container_name: meican-app_$MEICAN_INSTANCE
    volumes:
      - ../:/home/meican/meican-$MEICAN_INSTANCE
    tty: true
    restart: always
    ports:
      - "$MEICAN_PORT:80"
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:5.7
    container_name: meican-db_$MEICAN_INSTANCE
    volumes:
      - db-meican:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

volumes:
  db-meican: